### PR TITLE
add vendor dir

### PR DESCRIPTION
**Pull request by rphillips**
Adds the go modules within the vendor directory

### CODE REVIEW

**Comment by kannon92** [comment]
/hold

/lgtm
/approve

In case @harche or @asm582 have concerns.

**Comment by rphillips** [comment]
What sort of concerns would we have? Vendoring code brings guarantees that the dependency can be met, the dependency has not moved, and is highly available.

**Comment by kannon92** [comment]
/hold cancel

I think it is fine. I saw harshal tagged vitaly on this but I don't think there are any concerns here.

**Pull request merged**
