### PR TITLE
need to manage konflux dependencies with renovate

### PR DESCRIPTION
**Pull request by cpmeadors**
Konflux uses renovate to maintainer dependencies.  https://konflux.pages.redhat.com/docs/users/mintmaker/user.html#introduction  This needs to be enable with renovate.json that will override the default configurations.  I use a working configuration from another operator: https://github.com/openshift/trustee-operator/blob/main/renovate.json

Dependabot has been disabled so that we only have one dependency updating tool.

### CODE REVIEW

**Review by kannon92 — COMMENTED** [review]
Should we remove dependabot?

**Comment by kannon92** [comment]
This is concerning. https://konflux.pages.redhat.com/docs/users/mintmaker/user.html#list-of-currently-supported-managers

It looks like golang is not yet supported for konflux renovate.

**Comment by cpmeadors** [comment]
> This is concerning. https://konflux.pages.redhat.com/docs/users/mintmaker/user.html#list-of-currently-supported-managers
> 
> It looks like golang is not yet supported for konflux renovate.

The trustee operator I reference is go and it works fine there.  I also don't think we have a choice.  If we don't do this, then all the references to konflux dependencies aren't maintained and the pipeline will break.

**Comment by cpmeadors** [comment]
> Should we remove dependabot?

I am not clear on how the two would interact  I just know that konflux needs this.

**Comment by cpmeadors** [comment]
> > This is concerning. https://konflux.pages.redhat.com/docs/users/mintmaker/user.html#list-of-currently-supported-managers
> > It looks like golang is not yet supported for konflux renovate.
> 
> The trustee operator I reference is go and it works fine there. I also don't think we have a choice. If we don't do this, then all the references to konflux dependencies aren't maintained and the pipeline will break.

The upstream page https://docs.renovatebot.com/modules/manager/ seems to disagree with the konflux docs.  Golang looks supported there.

**Comment by cpmeadors** [comment]
> > Should we remove dependabot?
> 
> I am not clear on how the two would interact I just know that konflux needs this.
Based on a search in the konflux support slack channel, I see many other projects using dependabot as well as renovate.  No one is saying there is a conflict.

**Comment by rphillips** [comment]
probably should remove the dependabot config in the same pr.

**Comment by rphillips** [comment]
/override "Red Hat Konflux / dynamicacceleratorslicer-enterprise-contract / instaslice-operator-bundle"
/override "Red Hat Konflux / dynamicacceleratorslicer-enterprise-contract / instaslice-operator-controller"
/override "Red Hat Konflux / dynamicacceleratorslicer-enterprise-contract / instaslice-operator-daemonset"
/override "Red Hat Konflux / dynamicacceleratorslicer-enterprise-contract / pr group daemonset-installed-by-controller"

**Comment by rphillips** [comment]
/override "Red Hat Konflux / dynamicacceleratorslicer-enterprise-contract / instaslice-operator-bundle"
/override "Red Hat Konflux / dynamicacceleratorslicer-enterprise-contract / instaslice-operator-controller"
/override "Red Hat Konflux / dynamicacceleratorslicer-enterprise-contract / instaslice-operator-daemonset"
/override "Red Hat Konflux / dynamicacceleratorslicer-enterprise-contract / pr group daemonset-installed-by-controller"

**Pull request closed without merging**
