### PR TITLE
fix the typo in the finalizer e2e test

### PR DESCRIPTION
**Pull request by harche**
fix the typo in the finalizer e2e test

### CODE REVIEW

**Comment by harche** [comment]
```$ make lint 
golangci/golangci-lint info checking GitHub for tag 'v1.61.0'
golangci/golangci-lint info found version: 1.61.0 for v1.61.0/linux/amd64
golangci/golangci-lint info installed /home/harshal/go/src/github.com/openshift/instaslice-operator/bin/golangci-lint
/home/harshal/go/src/github.com/openshift/instaslice-operator/bin/golangci-lint run
WARN The linter 'exportloopref' is deprecated (since v1.60.2) due to: Since Go1.22 (loopvar) this linter is no longer relevant. Replaced by copyloopvar. 
test/e2e/e2e_test.go:164:49: `accelarator` is a misspelling of `accelerator` (misspell)
			finalizer := utils.AppendToInstaSlicePrefix("accelarator")
			                                             ^
make: *** [Makefile:154: lint] Error 1
``` 

it looks like the typo is in the code, not in the test. :)

**Comment by rphillips** [comment]
accel**e**rator is correct.

**Comment by harche** [comment]
I might be using slightly older version of the controller image (before the linter errors were fixed)

**Comment by harche** [comment]
The test fails for me because the test pod object has this `finalizers:[org.instaslice/accelarator]`

**Comment by kannon92** [comment]
@harche is this still relevant?

**Comment by harche** [comment]
> @harche is this still relevant?

nope.

/close

**Pull request closed without merging**
