### PR TITLE
Patching node memory capacity

### PR DESCRIPTION
**Pull request by mamy-CS**

### CODE REVIEW

**Comment by asm582** [comment]
@mamy-CS Thanks for the PR, the real fix would be done by adding node patch code here: https://github.com/openshift/instaslice-operator/blob/a6a9e7ad3869cfde334cbf7ea3ede479cbbc93af/internal/controller/instaslice_daemonset.go#L910
sample patch code for node : https://github.com/openshift/instaslice-operator/blob/a6a9e7ad3869cfde334cbf7ea3ede479cbbc93af/internal/controller/instaslice_daemonset.go#L480

I will do a LGTM once the build get is ok

**Comment by mamy-CS** [comment]
Yes I will create an issue for the real fix.

**Comment by asm582** [comment]
/lgtm

@mamy-CS As discussed, please put this code in the daemonset, this is needed for InstaSlice to be working in cluster setup

**Pull request merged**
