### PR TITLE
Upgrade to Kubernetes 1.31.1

### LINKED ISSUE #187: Upgrade to Kubernetes 1.31.
We should upgrade our Kubernetes dependencies to the latest release.

### PR DESCRIPTION
**Pull request by kannon92**
Upgrade Instaslice to Kubernetes 1.31.

Fixes #187 

Fixes #

### CODE REVIEW

**Comment by harche** [comment]
@kannon92 were you able to run e2e?

**Comment by kannon92** [comment]
Nope. I was a bit confused on how to run emulator mode e2e now.

**Comment by kannon92** [comment]
That would pull from the image in your repo. Plus I think those e2e tests assume a GPU.

**Comment by asm582** [comment]
> That would pull from the image in your repo. Plus I think those e2e tests assume a GPU.

you can add any repo to this command:

```
IMG=quay.io/amalvank/instaslicev2-controller-dev IMG_DMST=quay.io/amalvank/instaslicev2-daemonset-dev make <your-command>
```

**Comment by kannon92** [comment]
So looking at those e2e tests I see that they are also a GPU container. I don't know if those would run in emulator mode.

I can get a kind cluster working where I load the image and try a few smoke tests.

**Comment by kannon92** [comment]
/hold cancel

@harche @asm582 

I don't really like pushing images to a registry but I was able to build the images, load them into kind and run a few samples for the emulator pod.

Pods were scheduled.

@sairameshv is working on making the e2e tests easier to work with emulator mode and customer clusters so I think this is sufficient on my end.

**Comment by asm582** [comment]
@kannon92 Thanks for this PR, I have run daemonset shell scripts on the GPU node and they all pass. I would recommend we resolve merge conflicts if any post #194  is merged and again run tests before merging this PR.

**Comment by kannon92** [comment]
@asm582 looks like there wasn't any conflicts.

You want to give this your lgtm.

**Comment by kannon92** [comment]
/override "Red Hat Konflux / dynamicacceleratorslicer-enterprise-contract / instaslice-operator"
/override "Red Hat Konflux / dynamicacceleratorslicer-enterprise-contract / instaslice-operator-bundle"
/override "Red Hat Konflux / dynamicacceleratorslicer-enterprise-contract / instaslice-operator-daemonset"
/override "Red Hat Konflux / dynamicacceleratorslicer-enterprise-contract / pr group upgrade-k8s-1.30"

**Pull request merged**
